// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lenyovyegrjcegiucnex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlbnlvdnllZ3JqY2VnaXVjbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA5MTAsImV4cCI6MjA2NTU0NjkxMH0.WB6t2CnXTbJGNq1Mtg7_2NLSFK17UyDJ_r8P7DmgnFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);